spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgres://gngwuiokubxaeq:1f5f549b84a96e26eff5fde6f4d56103ef5ffee07b47577127ad2d3dacc380db@ec2-34-238-26-109.compute-1.amazonaws.com:5432/dcgilfkgnmi1i0
spring.datasource.username=gngwuiokubxaeq
spring.datasource.password=1f5f549b84a96e26eff5fde6f4d56103ef5ffee07b47577127ad2d3dacc380db
spring.mvc.view.suffix=.jsp